### ISSUE TITLE
The repository description is outdated

### ISSUE THREAD

**Issue by Calinou** [asilluron/hapi-mongoose#6]
The description of the repository states:

>  Hapi Plugin to handle Mongoose handshake and initial setup (Hapi v16 or below) 

As of v2.0.0, [it is compatible with hapi 17](https://github.com/asilluron/hapi-mongoose/pull/4) so the description should be updated as to not confuse users.

By the way, it looks like the v2.0.0 release wasn't tagged in the Git repository, even though it was published on npm.

**Comment by asilluron** [comment]
Thanks @Calinou ... apologies for the late reply 

https://github.com/asilluron/hapi-mongoose/releases/tag/v2.0.0
